theme: minima
title: My First Blog Post
author: Mahnoor123 Fatima
email: rohafatima90@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I am Mahnoor Fatima. A junior year student pursuing bachelors degree in Computer Science.
 I am skilled in C, C++ and Python programming languages.



# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
